sudo: required

language: node_js

node_js:
  - "8"

services:
  - docker

before_install:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t multicycles/api api;
    docker build -t multicycles/front front;
    fi

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push multicycles/api;
    docker push multicycles/front;
    fi

notifications:
  email: false